# Generated by Django 2.1.7 on 2019-09-18 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0015_auto_20190918_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 359577, tzinfo=utc))),
                ('Payment_Made_To', models.CharField(max_length=100)),
                ('Reason_For_Payment', models.CharField(choices=[('Mechanic', 'Car Repairing'), ('WaterBills', 'Water Bills'), ('Electricity', 'Electricity Bills'), ('URA', 'Paying Revenue')], max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Amount_In_Words', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 347037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 350057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 349059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 350057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 348064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 349273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 352054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 358739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 351053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 354046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 352054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 351053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 26, 353050, tzinfo=utc)),
        ),
    ]
