# Generated by Django 2.1.7 on 2019-09-18 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0016_auto_20190918_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 943231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 945219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 944191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 945219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 943231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 944191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 947251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainexpenses',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 949264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 948245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 946249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 948245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 946249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 946249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 6, 11, 30, 947251, tzinfo=utc)),
        ),
    ]
