# Generated by Django 2.1.7 on 2019-09-18 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0018_auto_20190918_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 679968, tzinfo=utc))),
                ('Payment_Made_To', models.CharField(max_length=100)),
                ('Reason_For_Payment', models.CharField(max_length=250)),
                ('Amount', models.IntegerField(default=0)),
                ('Amount_In_Words', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 673398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 675513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 674417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 675513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 673398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 674417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 677562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainexpenses',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 679968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 679382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 676390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 678384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 677562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 676390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 4, 43, 678384, tzinfo=utc)),
        ),
    ]
