# Generated by Django 2.1.7 on 2019-09-18 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0019_auto_20190918_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 424765, tzinfo=utc))),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Amount_In_Words', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 418780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 420776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 418780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 419778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 418780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 419778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 421806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainexpenses',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 423785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 423785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 420776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 422770, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='smallexpenses',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 424765, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 421806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 420776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 7, 29, 57, 422770, tzinfo=utc)),
        ),
    ]
